workflows:
  ios-app-store:
    name: iOS App Store Build
    integrations:
      app_store_connect: Magic
    environment:
      xcode: latest
      ios_signing:
        certificates:
          - Magic
        provisioning_profiles:
          - "Ary Perfumes"
          - "PUT_THE_EXTENSION_PROFILE_NAME_HERE"
    scripts:
      - name: Configure Xcode signing
        script: |
          xcode-project use-profiles --project "Ary Perfumes.xcodeproj"
      - name: Build IPA for App Store
        script: |
          xcode-project build-ipa \
            --project "Ary Perfumes.xcodeproj" \
            --scheme "Ary Perfumes"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
